### ISSUE TITLE
correcciones

### ISSUE THREAD

**Issue by lspigariol** [pdep-utn-frd/2019-tpwgame-grupo-de-paradigma#1]
estuve viendo el tp y me gusta.

@dani1882 @federiconguyen @braipablo 
bien por los sonidos y el movimiento
interesante la forma que modelan los disparos. ¿pensaron en que haya varias balas?

algunas cosas a tener en cuenta:

este metodo esta queriendo hacer lo mismo que las colisiones.  Tienen dos lugares donde "muere" el invasor y quitan el tick. 
fijense que el parametro `otro` lo estan ignorando, y el metodo se envia cuando ya saben con que colisionaron.

```
method chocarCon(otro) {
		if (self.position() == bala.position()) {
			game.removeVisual(self) 
			game.removeTickEvent("disparar") 
		}
		
		if (self.position() == nave.position()) {
			self.resetPreviousPosition()
		}
		self.resetPreviousPosition()
	}

```	

no esta bien hacer dos whenCollideDo del mismo objeto

```
game.whenCollideDo(invader, { personaje =>personaje.chocarCon(invader) })
game.whenCollideDo(invader, { proyectil =>	proyectil.chocarCon(invader)	})

```
tanto proyectil como personaje son dos variables locales del metodo, hacen referencia a cualquier cosa con la que colisiona el invader.
para aprovechar el polimorfismo, se peude pensar como `algo.esChocadoPor(invader)`

les quedo un metodo movimiento que no se usa y que no quedo bien

**Comment by lspigariol** [comment]
hola, tienen correcciones pendientes desde hace rato.
@dani1882  @federiconguyen  @braipablo

**Comment by braipablo** [comment]
Hola, hace unos días subimos unas correcciones.

**Comment by lspigariol** [comment]
hola, el trabajo esta mucho mejor
hay algun bug que hace que quiera quitar del tablero algo que ya no está.


un tema importante, que ya les habia comentado

game.whenCollideDo(invader, { personaje =>
			personaje.chocarCon(invader)
en ese linea, pesonaje es cualqueir cosa con la que el invader colisiona, no es necesariamente la nave, puede ser tambien la bala. Por eso esta bien que tanto bala como nave tengan el chocarCon.
Lo que esta de mas es la otra linea que tienen abajo, que intenta hacer nuevamente lo mismo
game.whenCollideDo(invader, { municion =>
			municion.chocarCon(invader)})

de todas maneras, el tp esta aprobado
